apiVersion: v1
kind: PersistentVolume
metadata:
  name: polyaxon-pv-upload
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.240.0.8  # Use the right IP
    path: "/data/upload"
  claimRef:
    namespace: polyaxon
    name: polyaxon-pvc-upload
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: polyaxon-pvc-upload
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
