apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: mnist
  labels:
    app: seldon
  namespace: seldon-system
spec:
  name: mnist
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: docker.dm-ai.cn/mlc/seldon-mnist:0.1
          imagePullPolicy: IfNotPresent
          name: classifier
    graph:
      endpoint:
        type: REST
      name: classifier
      type: MODEL
    labels:
      version: v1
    name: mnist
    replicas: 1
