apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: model-pkg-
spec:
  entrypoint: model-pkg-mnist
  
  volumes:
  # Pass my-existing-volume as an argument to the volumes-existing-example template
  # Same syntax as k8s Pod spec
  - name: work-volume
    persistentVolumeClaim:
    claimName: polyaxon-pvc-repos

  templates:
  - name: model-pkg
    steps:
    - - name: generate
        template: s2i

  - name: s2i
    container:
      image: danielfrg/s2i:1.0
      command: ["sh", "-c"]
      args: [""]
      volumeMounts:
      - name: workdir
        mountPath: /src
