---
version: 1

kind: experiment

environment:
  pytorch:
    n_workers: 1

declarations:
  batch_size_train: 128
  batch_size_test: 1000
  epochs: 5
  lr: 0.01
  train_steps: 400
  momentum: 0.5

build:
  image: docker.dm-ai.cn/mlc/pytorch:1.1-cuda10.0-cudnn7-py36
  build_steps:
    - pip install --no-cache-dir -U polyaxon-client==0.5.3

run:
  cmd: python3 distributed_run.py --batch-size={{ batch_size_train }} \
                                 --test-batch-size={{ batch_size_test }} \
                                 --epochs={{ epochs }} \
                                 --lr={{ lr }} \
                                 --momentum={{ momentum }}
